services:
  coffee.webapi:
    image: ${DOCKER_REGISTRY-}coffeewebapi
    container_name: offee.webapi
    build:
      context: .
      dockerfile: Services/Coffees/Presentation/Coffee.WebAPI/Dockerfile
    ports:
      - "5080:5080"
      - "5081:5081"
    volumes:
      - .:/usr/src/app/
      - /absolute/path/to/aspnetapp.pfx:/https/cert.pfx
    depends_on:
      - postgres
      - pgadmin
      - redis
    networks:
      - my_network

  identity.webapi:
    image: ${DOCKER_REGISTRY-}identitywebapi
    container_name: identity.webapi
    build:
      context: .
      dockerfile: Services/IdentityService/Presentation/Identity.WebAPI/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - .:/usr/src/app/
      - /absolute/path/to/aspnetapp.pfx:/https/cert.pfx
    depends_on:
      - postgres
      - pgadmin
      - redis
    networks:
      - my_network

  ocelot.apigateway:
    image: ${DOCKER_REGISTRY-}ocelotapigateway
    container_name: ocelot.apigateway
    build:
      context: .
      dockerfile: ApiGateways/Ocelot.ApiGateway/Dockerfile
    ports:
      - "9010:9010"
      - "9020:9020"
    volumes:
      - ./ApiGateways/Ocelot.ApiGateway/ocelot.json:/app/ocelot.json
      - /absolute/path/to/aspnetapp.pfx:/https/cert.pfx
    depends_on:
      - postgres
      - pgadmin
      - redis
      - coffee.webapi
      - identity.webapi
    networks:
      - my_network

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: CoffeeDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - my_network
  
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - my_network
  
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - my_network
    
  calconnect.papercut:
    image: changemakerstudiosus/papercut-smtp:latest
    container_name: Calconnect.papercut
    ports:
      - "8080:80"
      - "25:25"
    volumes:
      - ./dataprotection-keys:/home/app/.aspnet/DataProtection-Keys
    networks:
      - my_network

volumes:
  postgres-data:
  pgadmin-data:

networks:
  my_network:
    driver: bridge